### ISSUE TITLE
Combine with RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by adisiji** [TradeMe/MapMe#15]
Can we use it with [RealmRecyclerViewAdapter](https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java) ? If yes, would you mind to give the example ? 
Thanks

**Comment by josh-burton** [comment]
MapMe won't work with the RealmRecyclerViewAdapter out of the box - you'll need to write your own RealmMapMeAdapter that extends from a MapMeAdapter.

The  RealmRecyclerViewAdapter doesn't look too complex so copying over the realm logic shouldn't be difficult.

**Comment by adisiji** [comment]
Okay,
I will give a try
